---
# tasks file for ../playbooks_collection/roles/fresh_install/std_progs/
  - name: create folder
    win_file:
      path: C:\ansible_temp
      state: directory

  - name: download urls
    win_get_url:
      url: http://{{ iph }}/std_progs/{{ item }}
      dest: C:\ansible_temp\{{ item }}
    loop:
      - '7z1900-x64.exe'
      - 'AcroRdrDC1900820071_ru_RU.exe'
      - 'chrome.msi'

  - name: install 7Zip
    win_package:
      path: C:\ansible_temp\7z1900-x64.exe
      product_id: 7-Zip
      arguments: /S
      state: present
    become: yes
    become_method: runas

  - name: install acro reader DC
    win_package:
      path: C:\ansible_temp\AcroRdrDC1900820071_ru_RU.exe
      product_id: acrreadDC
      arguments: /S
      state: present
    become: yes
    become_method: runas

  - name: install Chrome
    win_package:
      path: C:\ansible_temp\chrome.msi
      state: present
    become: yes
    become_method: runas
