---
# tasks file for ../playbooks_collection/roles/fresh_install/remote_work/
  - name: create folder
    win_file:
      path: C:\ansible_temp
      state: directory

  - name: download urls
    win_get_url:
      url: http://{{ iph }}/remwork/{{ item }}
      dest: C:\ansible_temp\{{ item }}
    loop:
      - 'anyconnect.3.1.14018.exe'
      - 'AnyDesk-CM.msi'
      - 'tv12.exe'

  - name: install tv12
    win_package:
      path: C:\ansible_temp\tv12.exe
      product_id: tv12
      arguments: /S
      state: present
    become: yes
    become_method: runas

  - name: install anydesk
    win_package:
      path: C:\ansible_temp\AnyDesk-CM.msi
      state: present
    become: yes
    become_method: runas

  - name: unpack anyconnect
    win_command: C:\ansible_temp\remote\anyconnect.3.1.14018.exe /extract

  - name: install anyconnect
    win_package:
      path: C:\ansible_temp\remote\7CD12F2\WinSetup-Release-web-deploy.msi
      state: present
    become: yes
    become_method: runas
