---
# tasks file for ./playbooks_collection/roles/fresh_install/buh/
  - name: create folders
    win_file:
      path: C:\{{ item }}
      state: directory
    loop:
     - 'ansible'
     - 'ansible\1c'
#     - 'ansible\cp'

  - name: download urls
    win_get_url:
      url: http://{{ iph }}/buh/{{ item }}
      dest: C:\ansible_temp\{{ item }}
    loop:
      - 'cppro4.exe'
      - 'cppro5.exe'
      - '1c.zip'

  - block: #======= CryptoPRO5 ===========

    - name: install CryptoPRO5
      win_package:
        path: C:\ansible_temp\cppro5.exe
        product_id: cppro5
        arguments: -silent -nodlg
        state: present
      become: yes
      become_method: runas

    when: ccpro_ver_val == "5"

  - block: #======= CryptoPRO4 ===========
 
    - name: install CryptoPRO4
      win_package:
        path: C:\ansible_temp\cppro4.exe
        product_id: cppro4
        arguments: -silent -nodlg
        state: present
      become: yes
      become_method: runas

    when: ccpro_ver_val == "4"


  - name: unzip
    win_unzip:
      src: C:\ansible_temp\1c.zip
      dest: C:\ansible_temp\1c

  - name: install 1C
    win_package:
      path: C:\ansible_temp\1c\setup.exe
      product_id: 1C
      arguments: /S
      state: present
    become: yes
    become_method: runas
